In [4]:
import pandas as pd

In [6]:
data = pd.read_csv('Wiki Apple Music Data 2.csv')

In [7]:
data

,Apple ID Number,Apple Music Subscription,Artist Name,Build Version,Client IP Address,Device Identifier,End Position In Milliseconds,End Reason Type,Event End Timestamp,Event Reason Hint Type,...,Session Is Shared,Shared Activity Devices-Current,Shared Activity Devices-Max,Song Name,Source Type,Start Position In Milliseconds,Store Front Name,User’s Audio Quality,User’s Playback Format,UTC Offset In Seconds
0,8216579092,True,Montana of 300,"Music/3.1 iOS/14.4 model/iPhone11,6 hwp/t8020 ...",104.38.97.195,00008020-000E74E61E51002E,312516.0,NATURAL_END_OF_TRACK,2021-03-07T19:06:02.737Z,NOT_SPECIFIED,...,NaN,NaN,NaN,"Fighting Demons, Dropping Jewels",ORIGINATING_DEVICE,0,United States,NaN,NaN,-18000
1,8216579092,True,Nickelback,"Music/3.1 iOS/14.0.1 model/iPhone11,6 hwp/t802...",2607:fb90:371:7975:d901:ec62:66f0:c7fc,00008020-000E74E61E51002E,158772.0,PLAYBACK_MANUALLY_PAUSED,2020-10-31T19:18:51.879Z,NOT_SPECIFIED,...,NaN,NaN,NaN,Rockstar,ORIGINATING_DEVICE,0,United States,NaN,NaN,-14400
2,8216579092,True,"Pritam, Arijit Singh","Music/3.1 iOS/12.4.1 model/iPhone11,6 hwp/t802...",2607:fb90:3dc:2500:c12c:2693:133:f07a,00008020-000E74E61E51002E,72689.0,PLAYBACK_MANUALLY_PAUSED,2019-09-19T19:17:09.893Z,NOT_SPECIFIED,...,NaN,NaN,NaN,Saware,ORIGINATING_DEVICE,37890,United States,NaN,NaN,-14400
3,8216579092,True,"YoungBoy Never Broke Again, Juice WRLD","Music/3.1 iOS/14.4 model/iPhone11,6 hwp/t8020 ...",2607:fb90:372:2df0:756d:8aac:419d:63d1,00008020-000E74E61E51002E,0.0,SCRUB_END,2021-04-02T03:27:14.906Z,NOT_SPECIFIED,...,NaN,NaN,NaN,Bandit,ORIGINATING_DEVICE,68144,United States,NaN,NaN,-14400
4,8216579092,True,Farhan Akhtar,"Music/3.1 iOS/13.1.3 model/iPhone11,6 hwp/t802...",2607:fb90:3d8:b87:1965:7c1e:a130:f0f3,00008020-000E74E61E51002E,16425.0,TRACK_SKIPPED_FORWARDS,2019-12-01T03:34:03.817Z,NOT_SPECIFIED,...,NaN,NaN,NaN,Yeh Jaane Kaisa Raaz Hai,ORIGINATING_DEVICE,0,United States,NaN,NaN,-18000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105197,8216579092,True,Daft Punk,"Music/3.1 iOS/15.4.1 model/iPhone14,3 hwp/t811...",104.39.202.224,00008110-000834EE2151801E,109112.0,PLAYBACK_SUSPENDED,2022-05-14T16:53:25.782Z,NOT_SPECIFIED,...,False,NaN,NaN,Get Lucky (feat. Pharrell Williams & Nile Rodg...,ORIGINATING_DEVICE,0,United States,NaN,NaN,-14400
105198,8216579092,True,"Neeti Mohan, Kamaal Khan, Akasa Singh","Music/3.1 iOS/15.3.1 model/iPhone14,3 hwp/t811...",104.39.184.247,00008110-000834EE2151801E,30217.0,PLAYBACK_MANUALLY_PAUSED,2022-02-28T22:35:35.183Z,NOT_SPECIFIED,...,False,NaN,NaN,Aithey Aa,ORIGINATING_DEVICE,0,United States,NaN,NaN,-18000
105199,8216579092,True,Ed Sheeran,"Music/3.1 iOS/15.4.1 model/iPhone14,3 hwp/t811...",104.39.202.224,00008110-000834EE2151801E,157313.0,SCRUB_BEGIN,2022-05-01T17:05:13.794Z,NOT_SPECIFIED,...,False,NaN,NaN,Remember The Name (feat. Eminem & 50 Cent),ORIGINATING_DEVICE,57650,United States,NaN,NaN,-14400
105200,8216579092,True,Tanveer Evan,"Music/3.1 iOS/15.6 model/iPhone14,3 hwp/t8110 ...",104.38.33.154,00008110-000834EE2151801E,105188.0,PLAYBACK_SUSPENDED,2022-08-17T23:13:11.771Z,NOT_SPECIFIED,...,False,NaN,NaN,Maine Royaan (Lofi Remix),ORIGINATING_DEVICE,100923,United States,NaN,NaN,-14400
105201,8216579092,True,NaN,NaN,2607:fb90:3d5:3bfd:8593:1cd5:210f:8805,00008020-000E74E61E51002E,718086.0,NOT_APPLICABLE,2020-04-28T01:20:36.187Z,NOT_SPECIFIED,...,NaN,NaN,NaN,NaN,ORIGINATING_DEVICE,0,United States,NaN,NaN,0

In [10]:
#looking for most played artists in data
data.groupby(by = "Artist Name")['Artist Name'].count().sort_values(ascending = False).head(10)

Artist Name
Post Malone             4808
One Direction           3704
Metro Boomin            2513
Martin Garrix           2334
Ed Sheeran              2271
The Weeknd              1881
Maroon 5                1787
Arijit Singh            1568
Atif Aslam              1425
Pritam, Arijit Singh    1019
Name: Artist Name, dtype: int64

In [13]:
# looking for most played songs in data
data.groupby(by = "Song Name")['Song Name'].count().sort_values(ascending = False).head(10)

Song Name
Sunflower                       517
High on Life (feat. Bonn)       461
Blinding Lights                 448
Who Do You Love                 406
Circles                         400
Psycho (feat. Ty Dolla $ign)    339
Something Just Like This        333
Señorita                        312
Fine China                      297
Candy Paint                     294
Name: Song Name, dtype: int64

In [15]:
# looking for amount of artists played by the user 
len(data.groupby(by = "Artist Name")['Artist Name'].unique())

3185

In [16]:
# looking for the amount of songs played by the user
len(data.groupby(by = 'Song Name')['Song Name'].unique())

6582

In [18]:
# filtering data for song duration the user played 
filtered = data[["Song Name", "Milliseconds Since Play"]]
most_played = pd.DataFrame(filtered.groupby(by = "Song Name").max()).reset_index()

In [19]:
most_played[most_played['Milliseconds Since Play'] < 30000].head(30)

                                      Song Name  Milliseconds Since Play
0                                       !!!!!!!                      138
1                                     "Fiction"                       19
2                                 (Da Le) Yaleo                    21767
4                                        000000                      139
5                   1 2 3 (feat. Blac Youngsta)                      241
6                                  1 SIDED LOVE                      103
8                  1,2,3 dayz up (feat. SOPHIE)                      207
9                  1,2,3,4 (feat. Ed Robertson)                      371
12  10 Pieces for Piano, Op. 24: No. 9, Romance                       17
14                                   100 Rounds                      363
15                                    100 Shots                      168
16                                     100 Ways                       34
20             11 Minutes (feat. Travis Barker)                      174
21      1400 / 999 Freestyle (feat. Juice WRLD)                      376
22                                   15 Minutes                      139
23                                           16                       23
24                                     16 Shots                      117
25                                           18                      232
26                                  19 You + Me                      194
27                                      19-2000                      247
28                                         1973                      119
29                                         1982                      212
30                                         1997                      113
31                                          1mm                       12
32                                   1st & Goal                       34
33          1st n 3rd (feat. Lil Baby & Future)                      198
34                                     2 Phones                      217
35                  2 Vaults (feat. Lil Yachty)                      133
36                                       20 Min                       85
37                                        20/20                     2823